#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor DisplayPort-2 -d I II III
bspc monitor DisplayPort-0 -d IV V VI
bspc monitor DisplayPort-1 -d VII VIII IX

alt + {_,shift + }{1-9}
    bspc {desktop --focus,node --to-desktop} '{I,II,III,IV,V,VI,VII,VIII,IX}' 

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config active_border_color \#1E1E1E
bspc config normal_border_color \#141414

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Godot_Engine --name "research (DEBUG)" desktop='^9'

bspc rule -a RetroArch state=fullscreen
bspc rule -a retroarch state=fullscreen
bspc rule -a PPSSPPSDL state=floating fullscreen=on
bspc rule -a dolphin-emu state=fullscreen
bspc rule -a "PCSX2" state=fullscreen
bspc rule -a "Dolphin" state=fullscreen
bspc rule -a "mupen64plus" state=fullscreen




"$HOME"/.config/bspwm/autostart &
